# Generated by Django 4.2.6 on 2023-10-24 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Carro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total", models.PositiveIntegerField(default=0)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=400)),
                ("imagem", models.ImageField(upload_to="produtos")),
                ("preco", models.PositiveIntegerField()),
                ("venda", models.PositiveIntegerField()),
                ("descricao", models.TextField()),
                ("garantia", models.TextField(blank=True, max_length=300, null=True)),
                ("devolucao", models.CharField(blank=True, max_length=300, null=True)),
                ("visualizacao", models.PositiveIntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lojaapp.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pedido_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordernar_por", models.CharField(max_length=200)),
                ("endereco_envio", models.CharField(max_length=200)),
                ("telefone", models.CharField(max_length=200)),
                ("subtotal", models.PositiveIntegerField()),
                ("disconto", models.PositiveIntegerField()),
                (
                    "pedido_status",
                    models.CharField(
                        choices=[
                            ("Pedido Recebido", "Pedido Recebido"),
                            ("Pedido Processando", "Pedido Processando"),
                            ("Pedido Caminho", "Pedido Caminho"),
                            ("Pedido Completado", "Pedido Completado"),
                            ("Pedido Cancelado", "Pedido Cancelado"),
                        ],
                        max_length=200,
                    ),
                ),
                ("criando_em", models.DateTimeField(auto_now_add=True)),
                (
                    "carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lojaapp.carro"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_completo", models.CharField(max_length=200)),
                ("endereco", models.CharField(blank=True, max_length=200, null=True)),
                ("data_cadastro", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CarroProduto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avaliacao", models.PositiveIntegerField()),
                ("quantidade", models.PositiveIntegerField()),
                ("subtotal", models.PositiveIntegerField()),
                (
                    "carro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lojaapp.carro"
                    ),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lojaapp.produto",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="carro",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lojaapp.cliente",
            ),
        ),
    ]
