# Generated by Django 4.2.6 on 2023-10-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojaapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Promocao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dias", models.CharField(max_length=4)),
                ("horas", models.CharField(max_length=2)),
                ("minutos", models.CharField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name="produto",
            name="imagem",
            field=models.ImageField(upload_to="produtos/"),
        ),
    ]
