# Generated by Django 4.2.6 on 2023-10-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojaapp", "0002_promocao_alter_produto_imagem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promocao",
            name="dias",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="promocao",
            name="horas",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="promocao",
            name="minutos",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
