# Generated by Django 4.2.6 on 2023-10-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojaapp", "0003_alter_promocao_dias_alter_promocao_horas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocao",
            name="segundos",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
