# Generated by Django 4.2.6 on 2023-10-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lojaapp", "0004_promocao_segundos"),
    ]

    operations = [
        migrations.AddField(
            model_name="promocao",
            name="imagem",
            field=models.ImageField(default="", upload_to="promocao/"),
        ),
    ]
